ln -sf /venture/source_code/resource/bin/blender.desktop /venture/bin/blender
ln -sf /venture/source_code/resource/bin/designer.desktop /venture/bin/designer
ln -sf /venture/source_code/resource/bin/eclipse.desktop /venture/bin/eclipse
ln -sf /venture/source_code/resource/bin/krita.desktop /venture/bin/krita
ln -sf /venture/source_code/resource/bin/natron.desktop /venture/bin/natron
ln -sf /venture/source_code/resource/bin/pencil2d.desktop /venture/bin/pencil2d
ln -sf /venture/source_code/resource/bin/synfigStudio.desktop /venture/bin/synfigStudio
ln -sf /venture/source_code/resource/bin/maya2016.desktop /venture/bin/maya2016
ln -sf /venture/source_code/resource/bin/maya2017.desktop /venture/bin/maya2017
ln -sf /venture/source_code/resource/bin/maya2018.desktop /venture/bin/maya2018
ln -sf /venture/source_code/resource/bin/gimp.desktop /venture/bin/gimp